name: Deploy

on:
  push:
  schedule:
  - cron:  '30 20 * * *'

env:
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
  TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
  SERVERLESS_PLATFORM_VENDOR: tencent

jobs:
  serverless:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: use Node.js 12.16
      uses: actions/setup-node@v1
      with:
        node-version: "12.16"
    - run: |
        npm ci
        npm i -g serverless

    # 根据 github API 生成所有的 Issues
    - run: npm run issues

    # 编译为 js
    - run: npm run build

    # 整理 serverless 需要输出的 sls.js
    - run: mv index.js app.js
    - run: |
        cd ..
        sls --version
        sls registry


    - run: |
        rm -rf node_modules
        npm i --production

    # 设置腾讯云的 appid/secret，存储到 github 的 secrets 中
    # - name: deploy
    #   run: sls deploy --debug
